[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim" }
]

[open]
rules = [
    { name = "*.txt", use = "edit" },
    { name = "*.lua", use = "edit" },
    { name = "*.conf", use = "edit" },
    { name = "*.sh", use = "edit" },
    { name = "*.py", use = "edit" },
    { mime = "text/*", use = "edit" },
    { mime = "application/x-javascript", use = "edit" },
    # Standard-Regel für alle unbekannten Textdateien
    { mime = "inode/x-empty", use = "edit" }
]
